# Generated by Django 3.2.4 on 2021-12-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_rename_present_student_is_present'),
        ('projects', '0006_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.subject'),
        ),
    ]
