# Generated by Django 3.2.4 on 2021-12-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mail',
        ),
        migrations.AddField(
            model_name='seance',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
