# Generated by Django 3.2.4 on 2021-12-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20211205_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
